version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app
    volumes:
      - ./app:/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=contactform
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=contactform
      - TZ=Asia/Tokyo