import type { FormContent } from '@/lib/@types/form-content';
import type { ClientToServerEvents, ServerToClientEvents } from '@/lib/@types/models';
import { Box, Heading, Table, Tbody, Td, Th, Thead, Tr } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import type { Socket} from 'socket.io-client';
import { io } from 'socket.io-client';

const FormContents: NextPage = () => {

  const socket: Socket<ServerToClientEvents, ClientToServerEvents> = io(
    // サーバーのURLを指定
    'http://localhost:3001'
  );

  const [contents, setContents] = useState<FormContent[]>([]);

  const fetching = async () => {
    const req = await fetch('/api/form-contents');
    const { contents } = await req.json();
    setContents(contents);
  };

  // なぜか動かない
  socket.on('sync', () => {
    console.log('sync');
    fetching();
  });
  useEffect(() => {
    (() => {
      fetching();
    })();
  }, []);


  return <>
    <Head>
      <title>お問合せフォーム</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box>
      <Heading p={3} textAlign="center">お問合せ一覧</Heading>
      <Table>
        <Thead>
          <Tr>
            <Th>No</Th>
            <Th>名前</Th>
            <Th>メールアドレス</Th>
            <Th>内容</Th>
            <Th>送信日時</Th>
          </Tr>
        </Thead>
        <Tbody>
          {
            contents.map((item, index) => (
              <Tr key={index}>
                <Td>{item.id}</Td>
                <Td>{item.name}</Td>
                <Td>{item.email}</Td>
                <Td>{item.content_question}</Td>
                <Td>{item.postdate}</Td>
              </Tr>
            ))
          }
        </Tbody>
      </Table>
    </Box>
  </>;
};

export default FormContents;